### ISSUE TITLE
Project name inconsistent with script name

### ISSUE THREAD

**Issue by chrisjbillington** [anabanami/chonker#1]
The project name is "chonker" and the readme title is "chonker.py", but the main script is called "chunker.py". They should be the same.

Also, it would be better if the script was called just "chonker", instead of "chonker.py", and had a shebang so that you could run it just as `chonker infile outfile` instead of `python3 chonker infile outfile`, since it is not relevant to the user that it is written in Python.

**Comment by anabanami** [comment]
Fixed in: 10366ba3bf25246ff606b312ab009198245589d1
