### ISSUE TITLE
Not installable as a regular Python package

### ISSUE THREAD

**Issue by chrisjbillington** [anabanami/chonker#3]
It would be good if chonker were a regular Python package that could be installed by running `pip3 install chonker` or similar, such that after installing it that way, the `chonker` command was available from any directory instead of having to type the full path to the script or be in the same directory as it.

**Comment by shuttle1987** [comment]
See my project install automation scripts for how to get this up and running with a minimal amount of hassle.

**Comment by anabanami** [comment]
I think I succeded at making chonker a python package using test.pypi
Please let me know if it worked by it using this command:
`pip install -i https://test.pypi.org/simple/ chonker-anabanami`

I will update the README and close this issue if this worked.

**Comment by chrisjbillington** [comment]
Cool, looking good, but there are a few issues!

Firstly, the chonker script itself is not actually included in the tarball uploaded to test PyPI. You need to tell setup.py what files to include - you can make a list of files manually, but the easiest way is to use `setuptools_scm`, which will include all files that are being tracked by git, which is usually what you want. You can enable it by adding the keyword argument to `setup()`:

`setup_requires=['setuptools', 'setuptools_scm'],`

Then the `chonker` script will be included in the tarball. However, when pip downloads and installs the tarball, it won't actually install the chonker script (just because it's in the tarball doesn't mean pip knows where to install it to).

To tell setup.py to install the `chonker` script as a script (so that it puts it in `/usr/bin` or `/usr/local/bin` or wherever pip is configured to put scripts), you will need to add an extra argument to `setup()` in `setup.py`: `scripts=['chonker']`.

Then I think everything should be all good.

Normally none of this would be an issue and the argument `packages=setuptools.find_packages(),` that you included would have already done all this. But, that only works for python packages (i.e. modules that can be imported), not for stand-alone scripts, so the fact that chonker is a script and not a package makes it a bit different to other Python projects.

**Comment by anabanami** [comment]
Looks like another chonker already exists in PyPi.

![error](https://user-images.githubusercontent.com/59406352/77063656-2cc15c00-6a32-11ea-8188-28e6c93a1472.png)

This is the project:
https://pypi.org/project/chonker/#history

As of now I am taking name suggestions for this project C:

**Comment by anabanami** [comment]
I think I am leaning for megachonker
(chonks are 1MB size)
https://imgur.com/gallery/6FaoHXZ

heftyChonk is nice too.

**Comment by chrisjbillington** [comment]
Megachonker is great!

**Comment by anabanami** [comment]
megachonker is now an installable python package
:)
