### ISSUE TITLE
Doesn't preserve file attributes

### ISSUE THREAD

**Issue by chrisjbillington** [anabanami/chonker#5]
The files created/updated by chonker do not have their file attributes set to that of the original file they are supposed to be a copy of. It would be better if it did, so that after restoring a backed-up file, it was exactly the same as the original file. I noticed this because I run my backup script as root, and the backed-up files ended up being owned by root.

These attributes include created/modified/accessed time, the owner and group, and the execute/read/write permissions. There's probably some way to set these all at once based on some other file (i.e. the original file).

**Comment by anabanami** [comment]
Thanks for the help!

**Comment by chrisjbillington** [comment]
Looks like you forgot to import `shutil!`

```
Traceback (most recent call last):
  File "/usr/local/bin/megachonker", line 83, in <module>
    megachonker(args.in_file, args.out_file, quiet=args.quiet)
  File "/usr/local/bin/megachonker", line 58, in megachonker
    shutil.copystat(in_file, out_file)
NameError: name 'shutil' is not defined
```
